name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./find/pom.xml
          mvn clean package -f ./lost phone/pom.xml
          mvn clean package -f ./kt/pom.xml

      - name: Docker Build and push for Find
        uses: docker/build-push-action@v4
        with:
          context: ./find
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/find:latest
            ghcr.io/${{ github.repository }}/find:${{ github.ref_name }}
            
      - name: Docker Build and push for LostPhone
        uses: docker/build-push-action@v4
        with:
          context: ./lost phone
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/lost-phone:latest
            ghcr.io/${{ github.repository }}/lost-phone:${{ github.ref_name }}
            
      - name: Docker Build and push for Kt
        uses: docker/build-push-action@v4
        with:
          context: ./kt
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/kt:latest
            ghcr.io/${{ github.repository }}/kt:${{ github.ref_name }}
            
