apiVersion: apps/v1
kind: Deployment
metadata:
  name: kt
  labels:
    app: kt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kt
  template:
    metadata:
      labels:
        app: kt
    spec:
      containers:
        - name: kt
          image: "username/kt:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
