server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: find
          uri: http://localhost:8082
          predicates:
            - Path=/findManages/**, /views/**
        - id: lost phone
          uri: http://localhost:8083
          predicates:
            - Path=/remoteManages/**, /phones/**, 
        - id: kt
          uri: http://localhost:8084
          predicates:
            - Path=/customerManages/**, /deviceManages/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: find
          uri: http://find:8080
          predicates:
            - Path=/findManages/**, 
        - id: lost phone
          uri: http://lostPhone:8080
          predicates:
            - Path=/remoteManages/**, /phones/**, 
        - id: kt
          uri: http://kt:8080
          predicates:
            - Path=/customerManages/**, /deviceManages/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
